[env]
RUST_TEST_THREADS = "1"
CARGO_MAKE_RUN_CODECOV = "true"
RUSTFLAGS = "-D warnings"

# TODO: Remove this when cargo-make automatically runs the default rustfmt.
[tasks.format-stable]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.format]
dependencies = ["format-stable"]

[tasks.pre-verify-project]
dependencies = ["check-format", "clippy", "coverage-flow"]

[tasks.pre-coverage]
dependencies = ["test"]

[tasks.post-coverage]
dependencies = ["coverage-annotations"]

[tasks.coverage-annotations]
category = "CI"
description = "Verify the coverage annotations in the code"
install_crate = "cargo-coverage-annotations"
command = "cargo"
args = ["coverage-annotations"]
